FROM eclipse-temurin:21-jdk

# Install required packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv \
    python3-pip \
    curl \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Create virtual environment using the system Python 3 version
RUN python3 -m venv /opt/venv

# Set PATH to use venv by default
ENV PATH="/opt/venv/bin:$PATH"

# Upgrade pip and install build helpers in the virtual environment
RUN pip install --upgrade pip setuptools wheel

# Set working directory
WORKDIR /app/flask_app

# Copy only the requirements.txt initially to leverage Docker cache
COPY ../requirements.txt /app/flask_app/requirements.txt

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

RUN pip show elasticsearch

# Now copy the rest of your application
COPY . /app/flask_app

# Make port 5002 available outside this container
EXPOSE 5002

# Command to run the app
CMD ["python", "tpm_adapter.py"]